version: '3'

services:
  microservice1:
    build:
      context: ./microservice1
    ports:
      - "3000:3000"
    restart: always

  microservice2:
    build:
      context: ./microservice2
    ports:
      - "5000:5000"
    restart: always