apiVersion: v1
kind: ConfigMap
metadata:
  namespace: sock-shop
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'service1'
        static_configs:
          - targets: ['service1:8080']
      - job_name: 'service2'
        static_configs:
          - targets: ['service2:8080']