apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: junior20
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: omodionjunior:v1.0  # Update with your actual repository path
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent