apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: sock-shop
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer