apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: junior20
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 192.168.49.2:5000/microservice2:latest  # Update with your actual repository path
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent